
Book.destroy_all
Book.create!([
    {title: 'I Feel Bad About My Neck', description: 'Perhaps better known for her screenwriting (Silkwood, When Harry Met Sally, Heartburn), Ephron’s brand of smart theatrical humour is on best display in her essays. Confiding and self-deprecating, she has a way of always managing to sound like your best friend – even when writing about her apartment on New York’s Upper West Side. This wildly enjoyable collection includes her droll observations about ageing, vanity – and a scorching appraisal of Bill Clinton. '},
    {title: 'Broken Glass', description: 'The Congolese writer says he was “trying to break the French language” with Broken Glass – a black comedy told by a disgraced teacher without much in the way of full stops or paragraph breaks. As Mabanckou’s unreliable narrator munches his “bicycle chicken” and drinks his red wine, it becomes clear he has the history of Congo-Brazzaville and the whole of French literature in his sights. '},
    {title: 'The Girl With the Dragon Tattoo', description: 'Radical journalist Mikael Blomkvist forms an unlikely alliance with troubled young hacker Lisbeth Salander as they follow a trail of murder and malfeasance connected with one of Sweden’s most powerful families in the first novel of the bestselling Millennium trilogy. The high-level intrigue beguiled millions of readers, brought “Scandi noir” to prominence and inspired innumerable copycats. '},
    {title: 'Harry Potter and the Goblet of Fire', description: 'A generation grew up on Rowling’s all-conquering magical fantasies, but countless adults have also been enthralled by her immersive world. Book four, the first of the doorstoppers, marks the point where the series really takes off. The Triwizard Tournament provides pace and tension, and Rowling makes her boy wizard look death in the eye for the first time. '},
    {title: 'A Little Life', description: 'This operatically harrowing American gay melodrama became an unlikely bestseller, and one of the most divisive novels of the century so far. One man’s life is blighted by abuse and its aftermath, but also illuminated by love and friendship. Some readers wept all night, some condemned it as titillating and exploitative, but no one could deny its power.'},
    {title: 'Chronicles: Volume One', description: 'Dylan’s reticence about his personal life is a central part of the singer-songwriter’s brand, so the gaps and omissions in this memoir come as no surprise. The result is both sharp and dreamy, sliding in and out of different phases of Dylan’s career but rooted in his earliest days as a Woody Guthrie wannabe in New York City. Fans are still waiting for volume two. '},
    {title: 'The Tipping Point ', description: 'The New Yorker staff writer examines phenomena from shoe sales to crime rates through the lens of epidemiology, reaching his own tipping point, when he became a rock-star intellectual and unleashed a wave of quirky studies of contemporary society. Two decades on, Gladwell is often accused of oversimplification and cherry picking, but his idiosyncratic bestsellers have helped shape 21st-century culture.'},
    {title: 'Darkmans ', description: 'British fiction’s most anarchic author is as prolific as she is playful, but this freewheeling, visionary epic set around the Thames Gateway is her magnum opus. Barker brings her customary linguistic invention and wild humour to a tale about history’s hold on the present, as contemporary Ashford is haunted by the spirit of a medieval jester. '},
    {title: 'The Siege ', description: 'The Levin family battle against starvation in this novel set during the German siege of Leningrad. Anna digs tank traps and dodges patrols as she scavenges for wood, but the hand of history is hard to escape. '},
    {title: 'Light ', description: 'One of the most underrated prose writers demonstrates the literary firepower of science fiction at its best. Three narrative strands – spanning far-future space opera, contemporary unease and virtual-reality pastiche – are braided together for a breathtaking metaphysical voyage in pursuit of the mystery at the heart of reality. '},
    {title: 'Visitation ', description: 'A grand house by a lake in the east of Germany is both the setting and main character of Erpenbeck’s third novel. The turbulent waves of 20th-century history crash over it as the house is sold by a Jewish family fleeing the Third Reich, requisitioned by the Russian army, reclaimed by exiles returning from Siberia, and sold again. '},
    {title: 'Bad Blood ', description: 'A Whitbread prizewinning memoir, full of perfectly chosen phrases,
    that is one of the best accounts of family dysfunction ever written.
    Sage grew up with her grandparents, who hated each other: he was a drunken philandering vicar; his wife, having found his diaries,
    blackmailed him and lived in another part of the house. The
    author gets unwittingly pregnant at 16, yet the story has a happy
    ending. '},
    {title: 'Noughts & Crosses ', description: 'Set in an alternative Britain, this groundbreaking piece of young adult fiction sees black people, called the Crosses, hold all the power and influence, while the noughts – white people – are marginalised and segregated. The former children’s laureate’s series is a crucial work for explaining racism to young readers. '},
    {title: 'Priestdaddy ', description: 'This may not be the only account of living in a religious household in the American midwest (in her youth, the author joined a group called God’s Gang, where they spoke in tongues), but it is surely the funniest. The author started out as the “poet laureate of Twitter”; her language is brilliant, and she has a completely original mind.'},
    {title: 'Adults in the Room ', description: 'This memoir by the leather-jacketed economist of the six months he spent as Greece’s finance minister in 2015 at a time of economic and political crisis has been described as “one of the best political memoirs ever written”. He comes up against the IMF, the European institutions, Wall Street, billionaires and media owners and is told how the system works – as a result, his book is a telling description of modern power. '},
    {title: 'The God Delusion ', description: 'A key text in the days when the “New Atheism” was much talked about, The God Delusion is a hard-hitting attack on religion, full of Dawkins’s confidence that faith produces fanatics and all arguments for God are ridiculous. What the evolutionary biologist lacks in philosophical sophistication, he makes up for in passion, and the book sold in huge numbers. '},
])